import Head from 'next/head'
import { NavBar } from '../components/navbar/NavBar'

export default function Home() {
  return (
    <div className="bg-primary">
      <Head>
        <title>Denis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <NavBar />
       <div className="h-10"></div>
      </main>

      <footer>
        <h6>Copyright Denis Oluka</h6>
      </footer>
    </div>
  )
}
